# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3928fa2b01ba062122034abfbb16f175324199b05e7055898033a96e1766bf7256d799107617543e2432d5c6cd2c9e23d59c7a82b5f91dccd77dd0d394975f6

test:
  secret_key_base: 5d192f111698a3ee8aa5b4da08f03e7f29489e8313bd0035c2e7963a4280f68b3a1f3dec94e37b69d80f83acd95088c97f046537981d9242b26a9912be945f56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
